package com.elab.amortizaplus.presentation.screens.simulation.resources

/**
 * Mensagens específicas do fluxo de simulação.
 *
 * Centraliza textos para facilitar i18n e manutenção.
 */
object SimulationTexts {
    // Títulos e labels
    val screenTitle = "Simulação de Financiamento"
    val resultScreenTitle = "Resultado da Simulação"
    val formSectionTitle = "📋 Dados da Simulação"
    val financingAboutTitle = "Sobre o financiamento"
    val conditionsTitle = "Condições"
    val amortizationTypeTitle = "Tipo de amortização"
    val resultSectionTitle = "📊 Resumo da Simulação"
    val summaryWithoutTitle = "📈 Resumo - Sem Amortização Extra"
    val summaryWithTitle = "📉 Resumo - Com Amortização Extra"
    val savingsTitle = "🎯 Economia"
    val savingsInterestLabel = "Juros"
    val savingsTermLabel = "Prazo"
    val savingsTermEconomizedLabel = "Prazo economizado"
    // Campos do formulário
    val loanAmountLabel = "Valor do Empréstimo (R$)"
    val loanAmountPlaceholder = "Ex: 150000"
    val interestRateLabel = "Taxa de Juros (%)"
    val interestRatePlaceholder = "Ex: 13"
    val termsLabel = "Prazo (meses)"
    val termsPlaceholder = "Ex: 420"
    val termsUnitMonths = "meses"
    val startDateLabel = "Data de início (mês/ano)"
    val startDatePlaceholder = "Ex: 02/2026"
    // Opções
    val rateTypeAnnual = "Anual"
    val rateTypeMonthly = "Mensal"
    val systemSac = "SAC"
    val systemPrice = "PRICE"
    // Amortizações extras
    val extraAmortizationsTitle = "💰 Amortizações Extras"
    val extraAmortizationsEmpty = "Nenhuma amortização extra adicionada"
    val extraAmortizationsAddButton = "+ Adicionar amortização"
    val extraAmortizationsRemoveButton = "Remover"
    val extraAmortizationMonthLabel = "Mês"
    val extraAmortizationMonthPlaceholder = "Ex: 8"
    val extraAmortizationAmountLabel = "Valor"
    val extraAmortizationAmountPlaceholder = "Ex: 76000"
    val extraAmortizationReduceTerm = "Reduzir prazo"
    val extraAmortizationReducePayment = "Reduzir parcela"
    // Ações
    val calculateButton = "Calcular Simulação"
    val newSimulationButton = "Nova Simulação"
    val editSimulationButton = "Editar Simulação"
    val viewTableButton = "Ver Tabela Detalhada"
    val retryButton = "Tentar novamente"
    val moreOptions = "Mais opções"
    val tableTitle = "Tabela Detalhada"
    val tableSubtitle = "Detalhamento de parcelas e totais do cenário selecionado."
    val tableShowingWithExtra = "Mostrando parcelas com amortização extra"
    val tableShowingWithoutExtra = "Mostrando parcelas sem amortização extra"
    val tableToggleLabel = "Exibir amortizações extras"
    val tableControlsTitle = "Exibição"
    val tableScenarioLabel = "Cenário exibido"
    val tableScenarioWithExtra = "Com amortização extra"
    val tableScenarioWithoutExtra = "Sem amortização extra"
    val tableSummaryTitle = "Resumo do Cenário"
    val tableColumnsTitle = "Colunas"
    val tableColumnsHelper = "Selecione as colunas para exibir"
    val tableExtraHighlightLegend = "Valores de amortização extra aparecem em destaque"
    val tableTotalsLabel = "Totais"
    val tableBackButton = "Voltar"
    val tableMonthHeader = "Mês"
    val tableColumnAmortization = "Amortização"
    val tableColumnInterest = "Juros"
    val tableColumnInstallment = "Parcela"
    val tableColumnExtra = "Extra"
    val tableColumnBalance = "Saldo"
    val tableSummaryTotalPaid = "Total Pago"
    val tableSummaryTotalInterest = "Total de Juros"
    val tableSummaryTotalAmortized = "Total Amortizado"
    val tableSummaryTerm = "Prazo"
    val tableMissingTitle = "Sem simulação disponível"
    val tableMissingMessage = "Volte e calcule uma simulação para ver a tabela detalhada."
    // Histórico
    val historyTitle = "Histórico"
    val historyNavLabel = "Histórico"
    val simulationNavLabel = "Simular"
    val homeNavLabel = "Home"
    val homeTitle = "Amortiza+"
    val homePlaceholder = "Home (placeholder)"
    val homeMicrocopy = "Simule seu financiamento e veja quanto pode economizar antecipando parcelas."
    val homeLearnSectionTitle = "Aprenda"
    val homeLearnCard1Title = "O que é amortização?"
    val homeLearnCard1Body =
        "Amortizar é reduzir o saldo devedor antes do prazo. Isso pode diminuir os juros e o tempo do financiamento."
    val homeLearnCard2Title = "SAC vs PRICE"
    val homeLearnCard2Body =
        "No SAC, as parcelas tendem a cair com o tempo. Na PRICE, as parcelas são mais estáveis — mas os juros costumam pesar mais no início."
    val historyDetailTitle = "Detalhes da Simulação"
    val historyBackButton = "Voltar"
    val historyLoadingMessage = "Carregando histórico..."
    val historyEmptyTitle = "Nenhuma simulação salva"
    val historyEmptyMessage = "Calcule uma simulação para começar a montar seu histórico."
    val historyErrorTitle = "Não foi possível carregar o histórico"
    val historyLoadError = "Erro ao carregar histórico"
    val historyDeleteError = "Erro ao excluir simulação"
    val historyNotFound = "Simulação não encontrada"
    val historyTotalPaidLabel = "Total pago"
    val historyLastModifiedLabel = "Modificado"
    val historyResultTitle = "Resultado"
    val historyUseSimulationButton = "Editar e recalcular"
    val historyDeleteButton = "Excluir"
    // Estados
    val initialTitle = "Pronto para simular?"
    val initialDescription = "Preencha os dados acima e toque em Calcular Simulação."
    val errorTitle = "Não foi possível calcular"
    val errorDescriptionPrefix = "Detalhes:"
    val formInvalidMessage = "Por favor, preencha todos os campos corretamente"
    val inputProcessingError = "Erro ao processar dados de entrada"
    val calculationErrorPrefix = "Erro ao calcular:"
    val simulationNamePrefix = "Simulação"
    // Validação geral
    val requiredField = "Campo obrigatório"
    val invalidValue = "Valor inválido"
    val valueMustBeGreaterThanZero = "Valor deve ser maior que zero"
    val loanAmountMax = "Valor máximo: R$ 10.000.000"
    val invalidRate = "Taxa inválida"
    val rateMustBeGreaterThanZero = "Taxa deve ser maior que zero"
    val maxRate = "Taxa máxima: 30%"
    val invalidTerms = "Prazo inválido"
    val termsMustBeGreaterThanZero = "Prazo deve ser maior que zero"
    val maxTerms = "Prazo máximo: 600 meses (50 anos)"
    val invalidDate = "Data inválida (use MM/AAAA)"
    // Validação extras
    val extraMonthRequired = "Informe o mês"
    val extraMonthInvalid = "Mês inválido"
    val extraMonthTooLow = "Mês deve ser maior que zero"
    val extraMonthTooHighPrefix = "Mês deve ser ≤"
    val extraMonthDuplicate = "Mês já usado"
    val extraAmountRequired = "Informe o valor"
    val extraAmountInvalid = "Valor inválido"
    val extraAmountTooLow = "Valor deve ser maior que zero"
    // Estados
    val loadingMessage = "Calculando simulação..."
    // Resultados
    val totalPaidLabel = "Total Pago"
    val totalPaidWithoutLabel = "Total pago – sem amortização"
    val totalPaidWithLabel = "Total pago – com amortização"
    val totalInterestLabel = "Total de Juros"
    val monthsLabel = "Meses"
    val systemLabel = "Sistema"
    val valueLabel = "Valor"
    val rateLabel = "Taxa"
    val termLabel = "Prazo"
    val notAvailable = "-"
}
